"use client";

import pdfMake from "pdfmake/build/pdfmake";
import pdfFonts from "pdfmake/build/vfs_fonts";

// Register fonts
if (typeof window !== "undefined") {
  (pdfMake as any).vfs = (pdfFonts as any).pdfMake?.vfs || pdfFonts;
}

type PrescriptionData = {
  clinicName: string;
  branchName: string;
  doctorName: string;
  doctorReg: string;
  clinicPhone: string;
  patientName: string;
  patientAge: number;
  patientGender: string;
  patientId: string;
  date: string;
  diagnosis: string;
  items: { medicine: string; potency: string; dosage: string }[];
  instructions: string;
  followUpDate: string;
};

type InvoiceData = {
  invoiceNumber: string;
  clinicName: string;
  branchName: string;
  patientName: string;
  date: string;
  amount: string;
  method: string;
  status: string;
  gstin?: string;
};

export function downloadPrescriptionPDF(data: PrescriptionData) {
  const docDefinition: any = {
    pageSize: "A4",
    pageMargins: [40, 40, 40, 60],
    content: [
      // Header
      {
        columns: [
          {
            stack: [
              { text: data.clinicName, style: "clinicName" },
              { text: data.branchName, style: "branchInfo" },
            ],
          },
          {
            stack: [
              { text: data.doctorName, style: "doctorName", alignment: "right" },
              { text: `Reg. ${data.doctorReg} · ${data.clinicPhone}`, style: "doctorInfo", alignment: "right" },
            ],
          },
        ],
        margin: [0, 0, 0, 15],
      },
      { canvas: [{ type: "line", x1: 0, y1: 0, x2: 515, y2: 0, lineWidth: 1, lineColor: "#e2e8f0" }] },

      // Patient info
      {
        columns: [
          {
            stack: [
              { text: "PATIENT", style: "label" },
              { text: data.patientName, style: "value" },
              { text: `${data.patientAge} years · ${data.patientGender} · ${data.patientId}`, style: "subValue" },
            ],
          },
          {
            stack: [
              { text: "DATE", style: "label" },
              { text: data.date, style: "value" },
              { text: `Diagnosis: ${data.diagnosis}`, style: "subValue" },
            ],
            alignment: "right",
          },
        ],
        margin: [0, 15, 0, 15],
      },

      // Rx symbol
      { text: "Rx", style: "rxSymbol", margin: [0, 5, 0, 10] },

      // Medicines table
      {
        table: {
          headerRows: 1,
          widths: ["*", 80, "*"],
          body: [
            [
              { text: "Medicine", style: "tableHeader" },
              { text: "Potency", style: "tableHeader" },
              { text: "Dosage", style: "tableHeader" },
            ],
            ...data.items.map((item) => [
              { text: item.medicine, style: "tableCell" },
              { text: item.potency, style: "tableCell" },
              { text: item.dosage, style: "tableCell" },
            ]),
          ],
        },
        layout: {
          hLineWidth: () => 0.5,
          vLineWidth: () => 0,
          hLineColor: () => "#e2e8f0",
          paddingLeft: () => 8,
          paddingRight: () => 8,
          paddingTop: () => 6,
          paddingBottom: () => 6,
        },
        margin: [0, 0, 0, 20],
      },

      // Instructions
      { text: "INSTRUCTIONS", style: "label", margin: [0, 0, 0, 4] },
      { text: data.instructions || "No instructions provided.", style: "bodyText", margin: [0, 0, 0, 15] },

      // Follow-up
      { text: "NEXT FOLLOW-UP", style: "label", margin: [0, 0, 0, 4] },
      { text: data.followUpDate || "Not scheduled", style: "value", margin: [0, 0, 0, 30] },

      // Signature
      { canvas: [{ type: "line", x1: 0, y1: 0, x2: 515, y2: 0, lineWidth: 0.5, lineColor: "#e2e8f0" }] },
      {
        columns: [
          { text: "Digitally verified prescription\nGenerated by HomeoCare Pro Enterprise", style: "footerNote" },
          {
            stack: [
              { text: data.doctorName, style: "signatureName", alignment: "right" },
              { text: "Authorized signature", style: "signatureLabel", alignment: "right" },
            ],
          },
        ],
        margin: [0, 15, 0, 0],
      },
    ],
    styles: {
      clinicName: { fontSize: 16, bold: true, color: "#0f172a" },
      branchInfo: { fontSize: 9, color: "#64748b", margin: [0, 2, 0, 0] },
      doctorName: { fontSize: 11, bold: true, color: "#0f172a" },
      doctorInfo: { fontSize: 8, color: "#64748b", margin: [0, 2, 0, 0] },
      label: { fontSize: 8, color: "#94a3b8", bold: true, letterSpacing: 1 },
      value: { fontSize: 12, bold: true, color: "#0f172a" },
      subValue: { fontSize: 9, color: "#64748b", margin: [0, 2, 0, 0] },
      rxSymbol: { fontSize: 28, bold: true, color: "#0066ff", italics: true },
      tableHeader: { fontSize: 9, bold: true, color: "#64748b", fillColor: "#f8fafc" },
      tableCell: { fontSize: 10, color: "#0f172a" },
      bodyText: { fontSize: 10, color: "#334155", lineHeight: 1.5 },
      footerNote: { fontSize: 8, color: "#94a3b8" },
      signatureName: { fontSize: 11, bold: true, color: "#0f172a" },
      signatureLabel: { fontSize: 8, color: "#94a3b8" },
    },
  };

  pdfMake.createPdf(docDefinition).download(`Prescription_${data.patientName.replace(/\s/g, "_")}_${data.date}.pdf`);
}

export function downloadInvoicePDF(data: InvoiceData) {
  const docDefinition: any = {
    pageSize: "A4",
    pageMargins: [40, 40, 40, 60],
    content: [
      // Header
      {
        columns: [
          {
            stack: [
              { text: data.clinicName, style: "clinicName" },
              { text: data.branchName, style: "branchInfo" },
              data.gstin ? { text: `GSTIN: ${data.gstin}`, style: "branchInfo" } : {},
            ],
          },
          {
            stack: [
              { text: "TAX INVOICE", style: "invoiceTitle", alignment: "right" },
              { text: data.invoiceNumber, style: "invoiceNumber", alignment: "right" },
            ],
          },
        ],
        margin: [0, 0, 0, 20],
      },
      { canvas: [{ type: "line", x1: 0, y1: 0, x2: 515, y2: 0, lineWidth: 1, lineColor: "#e2e8f0" }] },

      // Invoice details
      {
        columns: [
          {
            stack: [
              { text: "BILL TO", style: "label" },
              { text: data.patientName, style: "value" },
            ],
          },
          {
            stack: [
              { text: "DATE", style: "label" },
              { text: data.date, style: "value" },
            ],
            alignment: "right",
          },
        ],
        margin: [0, 15, 0, 20],
      },

      // Summary table
      {
        table: {
          headerRows: 1,
          widths: ["*", 100, 80, 100],
          body: [
            [
              { text: "Description", style: "tableHeader" },
              { text: "Method", style: "tableHeader" },
              { text: "Status", style: "tableHeader" },
              { text: "Amount", style: "tableHeader", alignment: "right" },
            ],
            [
              { text: "Medical consultation & treatment", style: "tableCell" },
              { text: data.method, style: "tableCell" },
              { text: data.status, style: "tableCell", color: data.status === "Paid" ? "#10b981" : "#f59e0b" },
              { text: data.amount, style: "tableCell", alignment: "right", bold: true },
            ],
          ],
        },
        layout: {
          hLineWidth: () => 0.5,
          vLineWidth: () => 0,
          hLineColor: () => "#e2e8f0",
          paddingLeft: () => 8,
          paddingRight: () => 8,
          paddingTop: () => 8,
          paddingBottom: () => 8,
        },
        margin: [0, 0, 0, 20],
      },

      // Total
      {
        columns: [
          {},
          {
            stack: [
              {
                columns: [
                  { text: "Total:", style: "totalLabel", width: "auto" },
                  { text: data.amount, style: "totalValue", alignment: "right" },
                ],
              },
            ],
            width: 200,
          },
        ],
        margin: [0, 0, 0, 40],
      },

      // Footer
      { canvas: [{ type: "line", x1: 0, y1: 0, x2: 515, y2: 0, lineWidth: 0.5, lineColor: "#e2e8f0" }] },
      { text: "Thank you for choosing HomeoCare Pro.", style: "thankYou", margin: [0, 15, 0, 0] },
      { text: "This is a computer-generated invoice.", style: "footerNote", margin: [0, 4, 0, 0] },
    ],
    styles: {
      clinicName: { fontSize: 16, bold: true, color: "#0f172a" },
      branchInfo: { fontSize: 9, color: "#64748b", margin: [0, 2, 0, 0] },
      invoiceTitle: { fontSize: 14, bold: true, color: "#0066ff" },
      invoiceNumber: { fontSize: 11, color: "#64748b", margin: [0, 4, 0, 0] },
      label: { fontSize: 8, color: "#94a3b8", bold: true },
      value: { fontSize: 12, bold: true, color: "#0f172a", margin: [0, 3, 0, 0] },
      tableHeader: { fontSize: 9, bold: true, color: "#64748b", fillColor: "#f8fafc" },
      tableCell: { fontSize: 10, color: "#0f172a" },
      totalLabel: { fontSize: 13, bold: true, color: "#0f172a" },
      totalValue: { fontSize: 13, bold: true, color: "#0066ff" },
      thankYou: { fontSize: 11, color: "#334155", alignment: "center" },
      footerNote: { fontSize: 8, color: "#94a3b8", alignment: "center" },
    },
  };

  pdfMake.createPdf(docDefinition).download(`Invoice_${data.invoiceNumber}.pdf`);
}
